/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package booktify;

import booktify.scene.HomeScene;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
 
public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }
    
    @Override
    public void start(Stage stage) {
        HomeScene homeScene = new HomeScene(stage);
        homeScene.show();
        stage.setTitle("Booktify");
        stage.setResizable(false);
        stage.show();
    }
}
