/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package booktify;

import booktify.scene.LoginScene;
import javafx.application.Application;
import javafx.stage.Stage;
 
public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }
    
    @Override
    public void start(Stage stage) {
        LoginScene loginScene = new LoginScene(stage);
        loginScene.show();
        stage.setTitle("Booktify");
        stage.setResizable(false);
        stage.show();
    }
}
